FROM node:lts-alpine3.18 AS build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY *.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:latest as server

EXPOSE 3000

COPY qa-ui.nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/dist /usr/share/nginx/html

CMD [ "run", "--allow-net", "--allow-read", "--allow-env", "./dist/server/entry.mjs"]